version: '3.9'
services:

  main:
    container_name: portainerAgent
    image: portainer/agent:2.19.4-alpine # https://hub.docker.com/r/portainer/agent/tags?name=2.19.4-alpine
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /
        target: /host
      - type: bind
        source: ./volume/data
        target: /data
    environment:
      EDGE: 1
      EDGE_INSECURE_POLL: 0
    env_file: .env
