version: '3.9'
services:

  portainerAgent:
    container_name: portainerAgent
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
      - type: bind
        source: /
        target: /host
      - type: bind
        source: ./volume/data
        target: /data
    environment:
      EDGE: 1
      EDGE_INSECURE_POLL: 1
    env_file: .env
    image: portainer/agent
