version: '3.9'
services:

  main:
    container_name: scrutiny
    restart: unless-stopped
    image: ghcr.io/analogj/scrutiny:v0.7.2-omnibus # https://github.com/analogj/scrutiny/pkgs/container/scrutiny/versions?filters[version_type]=tagged
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - 1000:8080 # webapp
      - 1001:8086 # influxDB admin
    volumes:
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
      - type: bind
        source: ./volume/config
        target: /opt/scrutiny/config
      - type: bind
        source: ./volume/influx
        target: /opt/scrutiny/influxdb
    devices:
      - /dev/sda