version: '3.9'
services:

  main:
    container_name: scrutiny
    restart: unless-stopped
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 1000:8080 # webapp
      - 1001:8086 # influxDB admin
    volumes:
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
      - type: bind
        source: ./volume/config
        target: /opt/scrutiny/config
      - type: bind
        source: ./volume/influx
        target: /opt/scrutiny/influxdb
