version: '3.9'
services:

  main:
    container_name: wireguard
    image: linuxserver/wireguard:1.0.20210914 # https://hub.docker.com/r/linuxserver/wireguard/tags?name=1.0.20210914
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./volume/config
        target: /config
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      LOG_CONFS: true
      SERVERPORT: 51820
      PEERDNS: 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
      ALLOWEDIPS: 0.0.0.0/5,8.0.0.0/7,11.0.0.0/8,12.0.0.0/6,16.0.0.0/4,32.0.0.0/3,64.0.0.0/2,128.0.0.0/1,::/1,8000::/2,c000::/3,e000::/4,f000::/5,f800::/6,fc00::/8,fe00::/7
    env_file: .env