version: '3.9'
services:

  main:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:1.0.20210914
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./volume/config
        target: /config
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      LOG_CONFS: true
      SERVERPORT: 51820
      PEERDNS: 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
    env_file: .env