version: '3.9'
services:

  main:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    environment:
      VPN_INTERFACE: tunVpn
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: openvpn
      PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING: on
      TZ: Europe/Berlin
      OPENVPN_USER: ${piaUser:?}
      OPENVPN_PASSWORD: ${piaPassword:?}
      SERVER_REGIONS: ${piaRegion:?}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 3200:8000 # gluetun api
      - 9000:9000 # ?
    volumes:
      - type: bind
        source: ./volume/gluetun
        target: /gluetun
