version: '3.9'
services:

  main:
    image: qmcgaw/gluetun:v3.37.0 # https://hub.docker.com/r/qmcgaw/gluetun/tags?name=v3.37.0
    container_name: gluetun
    restart: unless-stopped
    environment:
      VPN_INTERFACE: tunVpn
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: openvpn
      PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING: enabled
      TZ: Europe/Berlin
      OPENVPN_USER: ${piaUser:?}
      OPENVPN_PASSWORD: ${piaPassword:?}
      SERVER_REGIONS: ${piaRegion:?}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 3200:8000 # gluetun api
    volumes:
      - type: bind
        source: ./volume/data
        target: /gluetun
