#cloud-config
hostname: arm
timezone: Europe/Berlin
users:
  - name: jaid
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBCPZ0ZiP841mcBLmSEU4c8zHkkYzpkBUlNPe6vJTCJz vps
    passwd: $6$EBJ1nzeuchahbpUx$Noktrb0iua3.MjRs6ji6BJA4WgD39/da7jtgVuYbZTyrh4nmEzKvTliXxi4eMs2LwBx74kpkkbiXD94SHZAUe/
    sudo: "ALL=(ALL) NOPASSWD: ALL"
ssh_genkeytypes: [ed25519]
apt: # See https://stackoverflow.com/a/71408252
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
      };
    };
    Acquire {
      Retries "60";
    };
    DPkg {
      Lock {
        Timeout "60";
      };
    };
package_upgrade: true
packages:
  - jq
  - git
manage_resolv_conf: true
resolv_conf:
  nameservers: ["1.1.1.1", "1.0.0.1"] # v6: 2606:4700:4700::1111 2606:4700:4700::1001
