#cloud-config
hostname: jaidMain
users:
  - name: jaid
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/4Cp9qpzDc2XNpZ9Qm69MDOHK4yAbuukwU7Ki3n6si8ZUzJXxWjGzf5mEeWVqjfHHZtbaXXFfL+1nWx9y/P2boldNKdU1Sgot18CISiFjjfdH+tUVuY3sVlKRM59AElgV2/rkIxY0on1Y9VG1iNla2gaBTKaazcUt40loPi/Cqn8O4xEh0ZX+4xwfuqCJdNX5y42+PgeW2cxT4PNAGj+uPI0Bw1HZVgMQJW0eckp4q7a5nJWUsOHW7eiUZNcE4vUmNAN1lZzNUzeL87kkFeOLZSNP0oZqaFmfL8BDpnplSOssWb2fskF/ynR5SjEWatzevNGd9y795Cl8CNWOB+ALS7/tVZVzTLkiiZJBQHSyhMCPjmqTvGnMmrD7DMKqEak9JWd8d22B93O8YV/QX+Qi3dOWkflad7tp6/xgIXSBDqlWHMF64HqF5j512776DMWnE9fU/hUOW+jMaXFRSjOx8Pyyvke1VwtlP3bHBAYVN7EIaXWPJ4AZ13nqKaORMdMJXBkCOMb+Dax8dXiRgaZytpfGBhyE7F1+d/CU2GcMS0jjcG/dbNc+PdscRrIPBBBI+xzBPZJFAscnsNwvwZvI0zqUg8Txrcf6YTvTzLxxO/KIo4byquR0fjZ43R3DZrExW1UNemqtyCm3lN3baBoMiipkw09njFBBgMmWNUvcOw== jaid.jsx@gmail.com
    sudo: "ALL=(ALL) NOPASSWD: ALL"
    # shell: /bin/bash #/usr/bin/zsh
    # groups: sudo
    ssh_import_id: jaidchen
package_upgrade: true
power_state:
  mode: reboot
  timeout: 60
packages:
  - build-essential
  - subversion
  - autoconf
  - libcppunit-dev
  - time
  - g++
  - gcc
  - ntp
  - libz-dev
  - comerr-dev
  - pkg-config
  - texinfo
  - cfv
  - libcurl3
  - libcurl4-openssl-dev
  - libtool
  - libssl-dev
  - libncurses5-dev
  - ncurses-term
  - libsigc++-2.0-dev
  - libcppunit-dev
  - libncursesw5-dev
  - libx264-dev
  - libnuma-dev
  - libvpx-dev
  - libmp3lame-dev
  - libopus-dev
  - libass-dev
  - x264
  - vpx-tools
  - libfreetype6-dev
  - libvorbis-dev
  - imagemagick
  - gettext
  - cmake
  - yasm
  - python3-pip
  - psmisc
  - ufw
  - htop
  - nano
  - unzip
  - fail2ban
manage_resolv_conf: true
resolv_conf:
  nameservers: ["1.1.1.1", "1.0.0.1"] # v6: 2606:4700:4700::1111 2606:4700:4700::1001
write_files:
  - path: /opt/bin/downloadFile
    permissions: 0755
    owner: root
    content: |
      #!/usr/bin/env bash
      curl --fail --silent --header "Cache-Control: no-cache" --location --retry 3 "$1" >"$2"
runcmd:
  - locale-gen --purge de_DE.UTF-8 en_US.UTF-8
  - update-locale
  - downloadFile https://raw.githubusercontent.com/Jaid/setup-server/master/commands/installNode /opt/bin/installNode
