version: '3.9'
services:

  main:
    container_name: samba
    image: crazymax/samba:4.18.9 # https://hub.docker.com/r/crazymax/samba/tags?name=4.18.9
    environment:
      TZ: Europe/Berlin
      SAMBA_HOSTS_ALLOW: 127.0.0.0/8 10.0.0.0/24
      SAMBA_SERVER_STRING: ${HOSTNAME:?}
      SAMBA_LOG_LEVEL: 2
    ports:
      - 445:445
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/${USER:?}
        target: /mnt/home
