version: "3.9"
services:
  app:
    container_name: github-release-writer
    image: jaidchen/github-release-writer
    restart: unless-stopped
    ports:
      - 39410:3000
      - 39411:3001
    volumes:
      - ./config:/home/app/.config/github-release-writer
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
