version: '3.9'
services:

  main:
    image: linuxserver/jackett:0.21.1835 # https://hub.docker.com/r/linuxserver/jackett/tags?name=0.21.1835
    container_name: jackett
    network_mode: container:gluetun
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - type: bind
        source: ./volume/config
        target: /config
      - type: bind
        source: /mnt/inbox
        target: /downloads
    restart: unless-stopped
