version: '3.9'
services:

  main:
    image: akhilrex/podgrab:1.0.0
    container_name: podgrab
    environment:
      CHECK_FREQUENCY: 60
      PGID: 1000
      PUID: 1000
    volumes:
      - type: bind
        source: ./volume/config
        target: /config
      - type: bind
        source: ./volume/data
        target: /assets
    ports:
      - 8030:8080
    restart: unless-stopped
