version: '3.9'
services:

  main:
    container_name: mediaMtx
    image: aler9/rtsp-simple-server
    restart: unless-stopped
    ports:
      - 554:554
      - 555:555
    volumes:
      - type: bind
        source: ./volume/config/config.yml
        target: /rtsp-simple-server.yml
        read_only: true
      - type: bind
        source: /usr/bin/ffmpeg
        target: /bin/ffmpeg
        read_only: true
