version: '3.9'
services:

  main:
    container_name: mediaMtx
    image: aler9/rtsp-simple-server
    restart: unless-stopped
    ports:
      - 554:8554
    volumes:
      - type: bind
        source: ./volume/config/config.yml
        target: /rtsp-simple-server.yml
        read_only: true
      - type: bind
        source: $HOME/bin
        target: /externalBin
        read_only: true
