version: "3.9"
services:

  caddy:
    image: jaidchen/caddy
    container_name: caddy
    volumes:
      - type: bind
        source: ./volume/Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: ./volume/static
        target: /usr/share/caddy
      - type: bind
        source: ./volume/data
        target: /data
      - type: bind
        source: ./volume/config
        target: /config
    environment:
      cloudflareApiToken: ${cloudflareToken:?}
    network_mode: host
    restart: unless-stopped
