#!/usr/bin/env bash
set -o errexit

mkdir --parents dist

cp -r composes dist/composes
cp -r services dist/services
cp -r timers dist/timers

outputFolder="dist/bin"
mkdir --parents "$outputFolder"

scriptsFolder=./commands
find "$scriptsFolder" -type f -printf '%P\0' | while read -r -d $'\0' file; do
  fileName=${file##*/}
  fileWithoutExtension=$(printf %s "$fileName" | sed 's|\.\w\+$||')
  inputFile="$scriptsFolder/$file"
  outputFile="$outputFolder/$fileWithoutExtension"
  printf '%s -> %s\n' "$inputFile" "$outputFile"
  cp "$inputFile" "$outputFile"
  git update-index --chmod=-x "$outputFile" # See https://stackoverflow.com/a/40979016/11389747
done
