#!/usr/bin/env bash
set -o errexit

mkdir --parents dist

cp -r composes dist/composes
cp -r files dist/files
cp -r services dist/services
cp -r timers dist/timers

outputFolder="dist/scripts"
mkdir --parents "$outputFolder"

scriptsFolder=./commands
find "$scriptsFolder" -type f -print0 | while read -r -d $'\0' file; do
  fileWithoutExtension=$(printf %s "$file" | sed 's|\.\w\+$||')
  inputFile="$scriptsFolder/$file"
  outputFile="$outputFolder/$fileWithoutExtension"
  printf '%s -> %s\n' "$inputFile" "$outputFile"
  cp "$inputFile" "$outputFile"
done
