version: "3.9"
services:

  app:
    container_name: github-release-writer
    image: jaidchen/github-release-writer
    restart: unless-stopped
    ports:
      - 39410:3000
      - 39411:3001
    volumes:
      - type: bind
        source: ./volume/config
        target: /home/app/.config/github-release-writer
