version: "3.9"
services:

  main:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      LOG_LEVEL: info
    ports:
      - 8191:8191
    restart: unless-stopped
