version: '3.9'
services:

  main:
    image: flaresolverr/flaresolverr:v3.3.15 # https://hub.docker.com/r/flaresolverr/flaresolverr/tags?name=v3.3.15
    container_name: flareSolverr
    environment:
      LOG_LEVEL: info
    ports:
      - 8191:8191
    restart: unless-stopped
