version: '3.9'
services:

  main:
    image: linuxserver/jellyfin:10.8.13 # https://hub.docker.com/r/linuxserver/jellyfin/tags?name=10.8.13
    container_name: jellyfin
    user: ${dockerUserId:?}:${dockerGroupId:?}
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./volume/config
        target: /config
      - type: bind
        source: ./volume/cache
        target: /cache
      - type: bind
        source: /mnt/storage/media
        target: /media
        read_only: true
    ports:
      - 8096:8096
      - 7359:7359/udp # Discover
      - 1900:1900/udp # DLNA
    environment:
      PUID: ${dockerUserId:?}
      PGID: ${dockerGroupId:?}
      TZ: Europe/Berlin
      JELLYFIN_PublishedServerUrl: ${jellyfinHost:?}
    cpu_shares: 2000
