name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Run compiler
        run: bash ./scripts/build
      - name: s0/git-publish-subdir-action
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
